import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Ai Image Gen',
  description: 'Generated by Amchia Mohamed with openai API',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-blue-50">{children}</body>
    </html>
  )
}
